// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recycler_view_Lukashevich.Data;

#nullable disable

namespace recycler_view_Lukashevich.API.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Русский писатель",
                            FirstName = "Лев",
                            LastName = "Толстой"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Русский писатель",
                            FirstName = "Фёдор",
                            LastName = "Достоевский"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Русский писатель",
                            FirstName = "Михаил",
                            LastName = "Булгаков"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Британская писательница",
                            FirstName = "Джоан",
                            LastName = "Роулинг"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Английский писатель",
                            FirstName = "Джон",
                            LastName = "Толкин"
                        },
                        new
                        {
                            Id = 6,
                            Biography = "Американский писатель",
                            FirstName = "Энди",
                            LastName = "Уир"
                        },
                        new
                        {
                            Id = 7,
                            Biography = "Английская писательница",
                            FirstName = "Джейн",
                            LastName = "Остен"
                        },
                        new
                        {
                            Id = 8,
                            Biography = "Немецкий писатель",
                            FirstName = "Эрих Мария",
                            LastName = "Ремарк"
                        },
                        new
                        {
                            Id = 9,
                            Biography = "Французский писатель",
                            FirstName = "Антуан",
                            LastName = "де Сент-Экзюпери"
                        },
                        new
                        {
                            Id = 10,
                            Biography = "Американский писатель",
                            FirstName = "Фрэнк",
                            LastName = "Герберт"
                        },
                        new
                        {
                            Id = 11,
                            Biography = "Русский писатель",
                            FirstName = "Сергей",
                            LastName = "Лукьяненко"
                        },
                        new
                        {
                            Id = 12,
                            Biography = "Колумбийский писатель",
                            FirstName = "Габриэль Гарсиа",
                            LastName = "Маркес"
                        },
                        new
                        {
                            Id = 13,
                            Biography = "Русский писатель",
                            FirstName = "Дмитрий",
                            LastName = "Глуховский"
                        },
                        new
                        {
                            Id = 14,
                            Biography = "Русский поэт",
                            FirstName = "Александр",
                            LastName = "Пушкин"
                        },
                        new
                        {
                            Id = 15,
                            Biography = "Русский писатель",
                            FirstName = "Николай",
                            LastName = "Гоголь"
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Лев Толстой",
                            AvailableQuantity = 5,
                            ISBN = "978-5-17-123456-7",
                            Publisher = "Эксмо",
                            Quantity = 5,
                            Title = "Война и мир",
                            Year = 1869
                        },
                        new
                        {
                            Id = 2,
                            Author = "Фёдор Достоевский",
                            AvailableQuantity = 2,
                            ISBN = "978-5-17-123457-4",
                            Publisher = "Азбука",
                            Quantity = 3,
                            Title = "Преступление и наказание",
                            Year = 1866
                        },
                        new
                        {
                            Id = 3,
                            Author = "Михаил Булгаков",
                            AvailableQuantity = 4,
                            ISBN = "978-5-17-123458-1",
                            Publisher = "АСТ",
                            Quantity = 4,
                            Title = "Мастер и Маргарита",
                            Year = 1967
                        },
                        new
                        {
                            Id = 4,
                            Author = "Лев Толстой",
                            AvailableQuantity = 4,
                            ISBN = "978-5-17-123459-8",
                            Publisher = "Эксмо",
                            Quantity = 6,
                            Title = "Анна Каренина",
                            Year = 1877
                        },
                        new
                        {
                            Id = 5,
                            Author = "Фёдор Достоевский",
                            AvailableQuantity = 3,
                            ISBN = "978-5-17-123460-4",
                            Publisher = "Азбука",
                            Quantity = 3,
                            Title = "Идиот",
                            Year = 1869
                        },
                        new
                        {
                            Id = 6,
                            Author = "Джоан Роулинг",
                            AvailableQuantity = 8,
                            ISBN = "978-5-17-123461-1",
                            Publisher = "Росмэн",
                            Quantity = 10,
                            Title = "Гарри Поттер и философский камень",
                            Year = 1997
                        },
                        new
                        {
                            Id = 7,
                            Author = "Джон Р.Р. Толкин",
                            AvailableQuantity = 6,
                            ISBN = "978-5-17-123462-8",
                            Publisher = "АСТ",
                            Quantity = 7,
                            Title = "Властелин колец",
                            Year = 1954
                        },
                        new
                        {
                            Id = 8,
                            Author = "Энди Уир",
                            AvailableQuantity = 5,
                            ISBN = "978-5-17-123463-5",
                            Publisher = "Эксмо",
                            Quantity = 5,
                            Title = "Марсианин",
                            Year = 2011
                        },
                        new
                        {
                            Id = 9,
                            Author = "Джейн Остен",
                            AvailableQuantity = 3,
                            ISBN = "978-5-17-123464-2",
                            Publisher = "Азбука",
                            Quantity = 4,
                            Title = "Гордость и предубеждение",
                            Year = 1813
                        },
                        new
                        {
                            Id = 10,
                            Author = "Эрих Мария Ремарк",
                            AvailableQuantity = 5,
                            ISBN = "978-5-17-123465-9",
                            Publisher = "АСТ",
                            Quantity = 6,
                            Title = "Три товарища",
                            Year = 1936
                        },
                        new
                        {
                            Id = 11,
                            Author = "Антуан де Сент-Экзюпери",
                            AvailableQuantity = 7,
                            ISBN = "978-5-17-123466-6",
                            Publisher = "Эксмо",
                            Quantity = 8,
                            Title = "Маленький принц",
                            Year = 1943
                        },
                        new
                        {
                            Id = 12,
                            Author = "Фрэнк Герберт",
                            AvailableQuantity = 5,
                            ISBN = "978-5-17-123467-3",
                            Publisher = "АСТ",
                            Quantity = 5,
                            Title = "Дюна",
                            Year = 1965
                        },
                        new
                        {
                            Id = 13,
                            Author = "Сергей Лукьяненко",
                            AvailableQuantity = 3,
                            ISBN = "978-5-17-123468-0",
                            Publisher = "Эксмо",
                            Quantity = 4,
                            Title = "Ночной дозор",
                            Year = 1998
                        },
                        new
                        {
                            Id = 14,
                            Author = "Габриэль Гарсиа Маркес",
                            AvailableQuantity = 5,
                            ISBN = "978-5-17-123469-7",
                            Publisher = "Азбука",
                            Quantity = 6,
                            Title = "Сто лет одиночества",
                            Year = 1967
                        },
                        new
                        {
                            Id = 15,
                            Author = "Дмитрий Глуховский",
                            AvailableQuantity = 8,
                            ISBN = "978-5-17-123470-3",
                            Publisher = "АСТ",
                            Quantity = 9,
                            Title = "Метро 2033",
                            Year = 2005
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 8
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 9
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 10
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 11
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 12
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 13
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.BookGenre", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 15
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Литературный жанр",
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Жанр с расследованием",
                            Name = "Детектив"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Научная фантастика",
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Жанр с магией",
                            Name = "Фэнтези"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Стихотворные произведения",
                            Name = "Поэзия"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Серьёзные произведения",
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Юмористические произведения",
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Приключенческий жанр",
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Хоррор",
                            Name = "Ужасы"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Напряжённый сюжет",
                            Name = "Триллер"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Историческая проза",
                            Name = "Исторический роман"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Сатирические произведения",
                            Name = "Сатира"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Документальная проза",
                            Name = "Публицистика"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Жизнеописание",
                            Name = "Биография"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Волшебные истории",
                            Name = "Сказка"
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DueDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            DueDate = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            DueDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            DueDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Overdue",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            DueDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Отличная книга!",
                            CreatedAt = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Comment = "Очень понравилась",
                            CreatedAt = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookId = 6,
                            Comment = "Лучшая книга!",
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 7,
                            Comment = "Неплохо, но затянуто",
                            CreatedAt = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            BookId = 8,
                            Comment = "Интересная идея",
                            CreatedAt = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@library.com",
                            FullName = "Администратор",
                            PasswordHash = "$2a$11$uEWHnMBbcBsCtwmTNxZrK.hibKLK2UWJM8p1XRP1c1KGdXm35MHtu",
                            RegistrationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivanov@mail.ru",
                            FullName = "Иван Иванов",
                            PasswordHash = "$2a$11$.k7ymrWs5VwCB03MKo5ezurEWm2MNwkLFSav29F92c/LiHONGcova",
                            RegistrationDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Librarian"
                        },
                        new
                        {
                            Id = 3,
                            Email = "petrova@mail.ru",
                            FullName = "Петрова Анна",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sidorov@mail.ru",
                            FullName = "Сидоров Сергей",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "kozlov@mail.ru",
                            FullName = "Козлов Дмитрий",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 6,
                            Email = "morozova@mail.ru",
                            FullName = "Морозова Елена",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 7,
                            Email = "novikov@mail.ru",
                            FullName = "Новиков Андрей",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 8,
                            Email = "fedotova@mail.ru",
                            FullName = "Федотова Ольга",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 9,
                            Email = "mikhailov@mail.ru",
                            FullName = "Михайлов Павел",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 10,
                            Email = "egorova@mail.ru",
                            FullName = "Егорова Наталья",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 11,
                            Email = "volkov@mail.ru",
                            FullName = "Волков Алексей",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 12,
                            Email = "tarasova@mail.ru",
                            FullName = "Тарасова Ирина",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 13,
                            Email = "zaitsev@mail.ru",
                            FullName = "Зайцев Игорь",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 14,
                            Email = "sokolova@mail.ru",
                            FullName = "Соколова Мария",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        },
                        new
                        {
                            Id = 15,
                            Email = "kuzmin@mail.ru",
                            FullName = "Кузьмин Артем",
                            PasswordHash = "pass123",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "User"
                        });
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.BookAuthor", b =>
                {
                    b.HasOne("recycler_view_Lukashevich.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recycler_view_Lukashevich.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.BookGenre", b =>
                {
                    b.HasOne("recycler_view_Lukashevich.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recycler_view_Lukashevich.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Loan", b =>
                {
                    b.HasOne("recycler_view_Lukashevich.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("recycler_view_Lukashevich.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Review", b =>
                {
                    b.HasOne("recycler_view_Lukashevich.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("recycler_view_Lukashevich.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookGenres");

                    b.Navigation("Loans");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("recycler_view_Lukashevich.Models.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
